### ISSUE TITLE
MD 

### ISSUE THREAD

**Issue by annalaczko** [BME-MIT-IET/iet-hf-2022-eqsch#13]
IET-HF.md-t megírtam

**Comment by annalaczko** [comment]
Cucumber MD-t befejeztem

**Comment by Farell-sudo** [comment]
Added JUnit.md - a4b7a4c6a021d254ae47230303949cd0532d7d11

**Comment by szomolagi** [comment]
ManualTests.md-t feltöltöttem - 5170d74b8903111120e6ac329e6e1e01f3646c82

**Comment by tektektek2000** [comment]
Added BuildFrameworkAndCi.md in 8a20df8d6c9e67a2f8aa130f874a48707da4ff95
